spring.application.name=${BD_NAME}
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
api.security.token.secret =${KEY_SECRET}
server.port=8080
spring.jpa.show-sql=true


# Actuator / Metrics
# management.endpoints.web.exposure.include=health,info,metrics,prometheus,threaddump
# management.endpoint.health.show-details=always
# management.metrics.export.prometheus.enabled=true


